"use strict";
var linklistnode_1 = require("./linklistnode");
var linklist_1 = require("./linklist");
var ll = new linklist_1.default;
var n1 = new linklistnode_1.default(1);
ll.insert(0, n1);
var n2 = new linklistnode_1.default(2);
ll.insert(0, n2);
var n3 = new linklistnode_1.default(3);
ll.insert(0, n3);
var n5 = new linklistnode_1.default(5);
ll.insert(0, n5);
var n6 = new linklistnode_1.default(6);
ll.insert(0, n6);
var n7 = new linklistnode_1.default(7);
ll.insert(0, n7);
var n8 = new linklistnode_1.default(8);
ll.insert(0, n8);
var n9 = new linklistnode_1.default(9);
ll.insert(0, n9);
ll.Circular(2);
ll.toCircular();
